### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by cour10eygrace** [cour10eygrace/OTC_synthesis_analyses#1]
- [x] remove sf files from data 
- [x] remove subsites not in analyses (WM 3700) --why was this site taken out??
- [x] clone and check functionality from desktop
